const SymptomData = [
  {
    keyword: 'chest pain',
    name: 'Chest Pain (Possible Cardiac)',
    shortResponse: 'Administer aspirin if available, keep patient calm, and prepare for cardiac support en route.',
    route: 'Main St → City Hospital Cardiology Wing',
    location: 'Apollo Emergency Hub, Sector 9',
    ambulanceType: 'Cardiac Ambulance',
    price: '₹3500',
    duration: '15-20 minutes',
    availableIn: 'Delhi, Mumbai, Bangalore',
  },
  {
    keyword: 'breathing',
    name: 'Difficulty Breathing (Possible Asthma or COPD)',
    shortResponse: 'Ensure patient is upright, administer inhaler if available, and transport urgently with oxygen support.',
    route: 'Green Ave → Metro General Hospital',
    location: 'OxygenCare Unit, Block B',
    ambulanceType: 'ICU Ambulance',
    price: '₹4000',
    duration: '10-15 minutes',
    availableIn: 'Kolkata, Chennai, Hyderabad',
  },
  {
    keyword: 'accident',
    name: 'Road Traffic Accident',
    shortResponse: 'Stop bleeding, immobilize if fracture suspected, and get trauma support en route.',
    route: 'Ring Road → Trauma Center Unit 3',
    location: 'TraumaPoint Sector 12',
    ambulanceType: 'Basic Life Support',
    price: '₹2000',
    duration: '5-10 minutes',
    availableIn: 'Jaipur, Pune, Ahmedabad',
  },
  {
    keyword: 'fainted',
    name: 'Loss of Consciousness',
    shortResponse: 'Check for responsiveness, monitor breathing, and rush for neurological and general evaluation.',
    route: 'Park Lane → City Neuro ICU',
    location: 'MedCity Hub, Zone C',
    ambulanceType: 'ICU Ambulance',
    price: '₹4500',
    duration: '12-18 minutes',
    availableIn: 'Lucknow, Surat, Indore',
  },
  {
    keyword: 'allergic',
    name: 'Severe Allergic Reaction (Anaphylaxis)',
    shortResponse: 'Administer epinephrine if trained, ensure airway is open, transport with urgent allergy management support.',
    route: 'Ashok Marg → Emergency Allergy Unit',
    location: 'FastAid Station, Phase 4',
    ambulanceType: 'Ventilator Ambulance',
    price: '₹5000',
    duration: '10-15 minutes',
    availableIn: 'Nagpur, Bhopal, Kochi',
  },
];

export default SymptomData;
